music-app/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: %i(create new show)
  resource :session, only: %i(create new destroy) 
  resources :bands do
    resources :albums, only: %i(new)
  end
  resources :albums, except: %i(new index)
end

music-app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  year       :integer          not null
#  band_id    :bigint           not null
#  album_type :boolean          default(TRUE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Album < ApplicationRecord
    ALBUM_TYPES = [true, false]
    validates :title, :year, presence: true
    validates :band_id, uniqueness: { scope: :title }
    validates :album_type, inclusion: { in: ALBUM_TYPES }

    belongs_to :band,
        foreign_key: :band_id,
        class_name: :Band
end

music-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

music-app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Band < ApplicationRecord
    validates :name, presence: true, uniqueness: true

    has_many :albums,
        foreign_key: :band_id,
        class_name: :Album,
        dependent: :destroy,
        inverse_of: :band
end

music-app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    attr_reader :password
    validates :email, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :password, length: { minimum: 6 }, allow_nil: true
    before_validation :ensure_session_token

    def self.find_by_credentials(email, password)
        @user = User.find_by(email: email)
        if @user && @user.is_password?(password)
            return @user
        else
            return nil
        end
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def reset_session_token!
        self.session_token = generate_unique_session_token
        self.save!
        self.session_token
    end

    private
    def generate_unique_session_token
        token = SecureRandom.urlsafe_base64
        while true
            if !User.exists?(session_token: token)
                return token
            end
        end
    end

    def ensure_session_token
        self.session_token ||= generate_unique_session_token
    end
end

music-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
        return @current_user
    end

    def logged_in?
        !!current_user
    end

    def login!(user)
        session[:session_token] = user.reset_session_token!
    end

    def logout
        current_user.reset_session_token!
        session[:session_token] = nil
        @current_user = nil
    end
end

music-app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
    before_action :set_band, only: %i(show edit update destroy)
    def new
        @band = Band.new
        render :new
    end

    def edit
        render :edit
    end

    def index
        @bands = Band.all
        render :index
    end

    def create
        @band = Band.new(band_params)
        if @band.save
            redirect_to bands_url
        else
            render :new
        end
    end

    def show
        render :show
    end

    def update
        @band.update(band_params)
    end

    def destroy
        @band.destroy
        redirect_to bands_url
    end

    private
    def set_band
        @band = Band.find_by(id: params[:id])
    end

    def band_params
        params.require(:band).permit(:name)
    end
end

music-app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
        @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        if @user
            login!(@user)
            redirect_to user_url(@user)
        else
            # flash.now[:messages] = ["Invalid Username or Password"]
            render :new
        end
    end

    def new
        render :new
    end

    def destroy
        logout
        redirect_to new_session_url
    end
end

music-app/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login!(@user)
            redirect_to user_url(@user)
        else
            flash[:messages] = @user.errors.full_messages
            render :new
        end
    end

    def show
        @user = User.find_by(id: params[:id])
        render :show
    end

    private
    def user_params
        params.require(:user).permit(:email, :password)
    end
end

music-app/app/helpers/application_helper.rb
module ApplicationHelper
    def auth_token
        "<input 
            type='hidden'
            name='authenticity_token'
            value='#{form_authenticity_token}'
        >".html_safe
    end
end

music-app/app/views/bands/index.html.erb
<div class="bands">
    <% @bands.each do |band| %>
        <a href="<%= band_url(band) %>"><%= band.name %></a>
        <br>
    <% end %>
    <br>
    <a href="<%= new_band_url %>">Create New Band</a>
</div>

music-app/app/views/bands/new.html.erb
<div class="form-parent">
    <h2>Create a Band!</h2>
    <form action="<%= bands_url %>" method="post">
        <%= auth_token %>
        <input type="text" name="band[name]" placeholder="Band Name">
        <center><input type="submit" value="Create" class="form-submit"></center>
    </form>
</div>

music-app/app/views/bands/show.html.erb
<div class="bands">
    <%= @band.name %>
    <a href="<%= bands_url %>">All Bands</a>
</div>

music-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag "reset" %>    
    <%= stylesheet_link_tag "application" %>   
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;700&display=swap" rel="stylesheet">
  </head>

  <header>
    <div class="header">
      <% if logged_in? %>
        <form action="<%= session_url %>" method="post" class="logout">
          <%= auth_token %>
          <input type="hidden" name="_method" value="delete">
          <input type="submit" value="Logout">
        </form>
      <% else %>
          <a href="<%= new_session_url %>">Sign In</a>
          <br>
          <a href="<%= new_user_url %>">Sign Up</a>
      <% end %>
    </div>
  </header>

  <body>
    <%= yield %>
    <% if flash[:messages] %>
      <% flash[:messages].each do |msg| %>
        <%= msg %>
      <% end %>
    <% end %>
  </body>
</html>

music-app/app/views/users/new.html.erb
<div class="form-parent">
    <h2>Sign Up!</h2>
    <form action="<%= users_url %>" method="post">
        <%= auth_token %>
        <input type="email" name="user[email]" placeholder="Email">
        <br><br>
        <input type="password" name="user[password]" placeholder="Password">
        <br><br>
        <center><input type="submit" value="Register" class="form-submit"></center>
    </form>
</div>

music-app/app/views/users/show.html.erb
<div class="welcome">
    <h2>Welcome <%= @user.email %>!</h2>
</div>